name: Docker Build Test

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter tag version (e.g., v1.2)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile
